version: '3.8'

services:
  back_drivers:
    build:
      context: .
    ports:
      - "8072:8072"
    volumes:
      - .:/app
    networks:
      - database_network


  postgres_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - database_network
      
networks:
  database_network:
    external: true