version: '3.8'

services:
  back_drivers:
    build:
      context: .
    ports:
      - "8072:8072"
    volumes:
      - .:/app
    networks:
      - database_network

networks:
  database_network:
    external: true